# Development-specific Docker Compose override
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: development
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Live code reloading for development
      - ./backend:/app/backend
      - ./server.py:/app/server.py
      - ./scores.json:/app/scores.json
    ports:
      - "8000:8000"
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Live code reloading for development
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    stdin_open: true
    tty: true